### ISSUE TITLE
PostalAccount Prefix

### ISSUE THREAD

**Issue by alain95** [z38/swiss-payment#12]
Not all common prefix are included in the array. 

I changed the code in \Z38\SwissPayment\PostalAccount\checkPrefix to the following:

return in_array($prefix, array(
            01, 10, 12, 13, 14, 16, 17, 18, 19,
            20, 23, 25, 28, 30, 34,
            40, 43, 44, 45, 46, 49, 50, 53, 56,
            60, 65, 69, 70, 80,
            82, 84, 85, 87, 90,
            91, 92,
        ));

**Comment by z38** [comment]
Thank you for reporting this issue. It really looks like some prefixes are missing:

| SwissPayment | SIX | alain95 |
| --: | :-: | :-- |
|  |  | 01 |
| 10 | 10 | 10 |
|  | 11 |  |
| 12 | 12 | 12 |
|  | 13 | 13 |
|  | 14 | 14 |
|  |  | 16 |
| 17 | 17 | 17 |
| 18 | 18 | 18 |
| 19 | 19 | 19 |
| 20 | 20 | 20 |
| 23 | 23 | 23 |
| 25 | 25 | 25 |
|  |  | 28 |
| 30 | 30 | 30 |
|  | 31 |  |
| 34 | 34 | 34 |
| 40 | 40 | 40 |
|  | 41 |  |
|  |  | 43 |
|  |  | 44 |
| 45 | 45 | 45 |
| 46 | 46 | 46 |
| 49 | 49 | 49 |
| 50 | 50 | 50 |
|  |  | 53 |
|  |  | 56 |
| 60 | 60 | 60 |
|  | 61 |  |
| 65 | 65 | 65 |
| 69 | 69 | 69 |
| 70 | 70 | 70 |
| 80 | 80 | 80 |
|  | 81 |  |
| 82 | 82 | 82 |
| 84 | 84 | 84 |
| 85 | 85 | 85 |
| 87 | 87 | 87 |
|  | 88 |  |
|  | 89 |  |
| 90 | 90 | 90 |
| 91 | 91 | 91 |
| 92 | 92 | 92 |

How did you discover these additional prefixes? Do you have a source or acquired them using real live data? I'm not sure whether we should ditch the whole prefix check altogether...

**Comment by alain95** [comment]
My additional prefixes are based on our existing database, which we're using at the moment. I also tried to find an official list / source for postal code prefixes, but i didn't find anything helpful on the web. 
But what surprises me is the fact that in your list of SIX prefixes 01 isn't listed, this is a very common prefix in switzerland, so i don't know if you should go with the list of SIX or you should ditch this whole check...

**Comment by z38** [comment]
The 01 prefix is indeed quite common. I just checked my source and saw that these are handled differently because they are actually ESR particpant numbers.

As I didn't find any official prefix list either, I [replaced](https://github.com/z38/swiss-payment/commit/3ad45aa957c9b98c3238ef92d4b8e9b240814b34) the prefix check with one that calculates the check digit. This should improve the detection rate of invalid numbers and frees us from maintaining a prefix list.

In case you have some spare time left, I would be glad to hear if your data records do pass the validation.

**Comment by z38** [comment]
The improved validation procedure is now part of [v0.5.0](https://github.com/z38/swiss-payment/releases/tag/v0.5.0). Feel free to reopen this issue if you encounter any problems.
