### ISSUE TITLE
Incompatibility with new format version?

### ISSUE THREAD

**Issue by zelding** [z38/swiss-payment#16]
I'm currently in the process of upgrading to the new format, but the 0.5 version seems to generate invalid xml files.

`xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03 pain.001.001.03.xsd"`

The issues according to the ubs validator:

```
<InitgPty>
    <Nm>DAgency</Nm>
    <CtctDtls>
         <Nm>Z38_SwissPayment</Nm>
         <Othr>0.5.0</Othr>
    </CtctDtls>
</InitgPty>
```
The error seems to indicate the `CtctDtls` is deprecated
`Invalid content was found starting with element 'CtctDtls'. One of '{"urn:iso:std:iso:20022:tech:xsd:pain.001.001.03":Id}' is expected.`

```
<PmtInf>
    <PmtInfId>506 EUR</PmtInfId>
    <PmtMtd>TRF</PmtMtd>
    <BtchBookg>true</BtchBookg>
    <ReqdExctnDt>2018-03-05</ReqdExctnDt>
    <Dbtr>
        <Nm>DAgency</Nm>
    </Dbtr>
```

The other one seems to require the transaction count in this part too:

`Invalid content was found starting with element 'ReqdExctnDt'. One of '{"urn:iso:std:iso:20022:tech:xsd:pain.001.001.03":NbOfTxs}' is expected.`

Am I doing something wrong?

**Comment by sdespont** [comment]
**My questions :**
You wrote in the title that it is not working with "new format version" : what does it mean?
Do you know if previous versions was successfully checked by UBS?

**About your first question :**

The norm says at [point 1.8 page 21](https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/archives/implementation-guidelines-ct/implementation-guidelines-ct_v1_8_181217.pdf) that 

> At least one of the two elements "Name" or "Identification" must be sent

So, using `<Nm>` and not `<Id>` must be ok.

**About your second question :**

The norm says about `<NbOfTxs>` at [point 2.4 page 24](https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/archives/implementation-guidelines-ct/implementation-guidelines-ct_v1_8_181217.pdf) that it is an **optional** field :

> Not generally checked by Swiss institutions. Checking uses the corresponding element at A-Level.

So, it must not throw an error either. As `<NbOfTxs>` element at A-level is mandatory, can you check that it is present? I am sure the answer is YES because the error would be given by UBS if not, but...

You should contact them to understand why they are not respecting the standard.

**Comment by z38** [comment]
@zelding Thank you for your feedback. I agree with @sdespont that the errors mentioned seem to be a bit odd. What tool did you use to verify the validity?

I usually use https://ubs-paymentstandards.ch/ to validate my messages which does not throw any errors with version 0.5 for me. The errors might come from the used schema (`urn:iso:std:iso:20022:tech:xsd:pain.001.001.03.xsd` vs. `http://www.six-interbank-clearing.com/de/pain.001.001.03.ch.02.xsd`). Even though it was my understanding that even with the Swiss modifications any message should pass the official ISO schema.

Update: I did a quick test with a few messages and they pass [pain.001.001.03](https://www.iso20022.org/message_archive.page#PaymentsInitiation3) without errors.

**Comment by zelding** [comment]
The issue was my predecessor forked the repo and meddled with all kinds of things, once I've reverted to the official all errors went away. Thank you for your help!
